export const endpoints = {
  login: "/authentication/v1/login/",
  restaurantList: "/restaurant/v1/restaurant",
  addRestaurant: "/restaurant/v1/restaurant/",
  ownerList: "/user/v1/list",
  editRestaurant: "/restaurant/v1/restaurant",
  deleteRestaurant: "/restaurant/v1/restaurant",
  menuList: "/restaurant/v1/menu",
  addMenu: "/restaurant/v1/menu/",
  editMenu: "/restaurant/v1/menu",
  deleteMenu: "/restaurant/v1/menu",
  menuItemList: "/restaurant/v1/menu_item",
  menuItemDetails: "/restaurant/v1/menu_item",
  deleteMenuItem: "/restaurant/v1/menu_item",
  addMenuItem: "/restaurant/v1/menu_item/",
  editMenuItem: "/restaurant/v1/menu_item",
  employeeList: "/restaurant/v1/employee",
  addEmployee: "/restaurant/v1/employee/",
};
